inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3.0

RSpec/ExampleLength:
  Enabled: false
