# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |_coding_dojo| "https://github.com/mamaevdev/coding-dojo" }

gem "rspec", "~> 3.13"
gem "rubocop-rspec", "~> 2.29"
gem "standard", "~> 1.35"
